nuxeo:
  enabled: false
mongodb:
  enabled: true
postgresql:
  enabled: false
opensearch:
  enabled: false
elasticsearch7:
  enabled: false
elasticsearch8:
  enabled: true
kafka:
  enabled: true
redis:
  enabled: true
