nuxeo:
  enabled: false
mongodb:
  enabled: false
postgresql:
  enabled: false
opensearch:
  enabled: false
elasticsearch7:
  enabled: false
elasticsearch8:
  enabled: false
kafka:
  enabled: false
redis:
  enabled: true
