extra-deploy:
  enabled: true
nuxeo:
  enabled: false
mongodb:
  enabled: false
postgresql:
  enabled: true
opensearch:
  enabled: true
elasticsearch7:
  enabled: false
elasticsearch8:
  enabled: false
kafka:
  enabled: true
redis:
  enabled: true
