extra-deploy:
  enabled: false
nuxeo:
  enabled: false
mongodb:
  enabled: true
postgresql:
  enabled: false
opensearch:
  enabled: true
elasticsearch7:
  enabled: false
elasticsearch8:
  enabled: false
kafka:
  enabled: true
redis:
  enabled: true
