{{- $valuesDir := ternary "unittests" .Environment.Name (regexMatch "^.*UnitTests$" .Environment.Name) -}}
repositories:
- name: bitnami
  # use a specific version of index.yaml from the git repository as Bitnami removes all charts older than 6 months from
  # the head index.yaml descriptor, see https://github.com/bitnami/charts/issues/10539
  url: https://raw.githubusercontent.com/bitnami/charts/d2a3b454f8bb808a493d417199d3e2e09b5c650c/bitnami
- name: bitnami-redis
  # use a specific version of index.yaml for redis as it's old
  url: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
- name: opensearch
  url: https://opensearch-project.github.io/helm-charts/
- name: nuxeo
  url: https://chartmuseum.platform.dev.nuxeo.com/

helmDefaults:
  timeout: 600
  wait: true

releases:
- name: nuxeo
  chart: nuxeo/nuxeo
  version: 3.0.1
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: nuxeo.enabled
  {{ if eq .Environment.Name "benchmark" }}
  needs:
  - mongodb
  - opensearch
  - kafka
  {{ end }}
  values:
  - values/values-nuxeo.yaml.gotmpl
  - values/{{ $valuesDir }}/values-nuxeo.yaml.gotmpl
- name: mongodb
  chart: bitnami/mongodb
  version: 13.3.1
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: mongodb.enabled
  values:
  - values/values-mongodb.yaml.gotmpl
  - values/{{ $valuesDir }}/values-mongodb.yaml.gotmpl
- name: postgresql
  chart: bitnami/postgresql
  version: 10.16.2 # latest chart version for app version 13
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: postgresql.enabled
  values:
  - values/values-postgresql.yaml.gotmpl
  - values/{{ $valuesDir }}/values-postgresql.yaml
- name: opensearch
  chart: opensearch/opensearch
  version: 1.16.0
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: opensearch.enabled
  values:
  - values/values-opensearch.yaml.gotmpl
  - values/{{ $valuesDir }}/values-opensearch.yaml.gotmpl
- name: kafka
  chart: bitnami/kafka
  version: 19.1.3
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: kafka.enabled
  values:
  - values/values-kafka.yaml.gotmpl
  - values/{{ $valuesDir }}/values-kafka.yaml.gotmpl
- name: redis
  chart: bitnami-redis/redis
  version: 11.2.1
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: redis.enabled
  values:
  - values/values-redis.yaml.gotmpl
  - values/{{ $valuesDir }}/values-redis.yaml

environments:
  runtimeUnitTests:
    values:
    - environments/unit-tests-runtime.yaml
  devUnitTests:
    values:
    - environments/unit-tests-dev.yaml
  mongodbUnitTests:
    values:
    - environments/unit-tests-mongodb.yaml
  postgresqlUnitTests:
    values:
    - environments/unit-tests-postgresql.yaml
  benchmark:
    values:
    - environments/benchmark.yaml
